# Railway.app deployment configuration
# This file tells Railway how to deploy your app

[build]
builder = "DOCKERFILE"
dockerfilePath = "container.dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/"
healthcheckTimeout = 300