services:
  - type: web
    name: pharmida-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: ""
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: ""
      - key: RAZORPAY_KEY_SECRET
        value: ""
      - key: EMAIL_USER
        value: ""
      - key: EMAIL_PASS
        value: ""
      - key: FIREBASE_ADMIN_JSON
        value: ""
      - key: FIREBASE_STORAGE_BUCKET
        value: pharmida-healthcare.appspot.com