services:
  - type: web
    name: pharmida-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
    # Add your environment variables in Render dashboard:
    # - RAZORPAY_KEY_ID
    # - RAZORPAY_KEY_SECRET  
    # - EMAIL_USER
    # - EMAIL_PASS