services:
  - type: web
    name: pharmida-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PASSWORD
        value: admin123
      - key: JWT_SECRET
        generateValue: true